# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('styles', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField()),
                ('title', models.CharField(max_length=155)),
                ('subtitle', models.CharField(max_length=155)),
                ('content', models.TextField()),
                ('summary', models.CharField(max_length=155)),
                ('media', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRF', 'Draft'), ('PUB', 'Published')], default='DRF', max_length=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
