# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRF', 'Draft'), ('PUB', 'Published'), ('DEL', 'Deleted')], default='DRF', max_length=3),
        ),
    ]
