# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20171004_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_slug',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('title', 'owner')]),
        ),
    ]
