version: '2'
services:
    postgres:
        image: postgres:9.6.5
    wellcoders:
        image: registry.gitlab.com/wellcoders/wellcoders_backend
        volumes:
            - .:/app
            - ../logs:/logs
        command: sh develop.sh
        working_dir: /app
        ports:
            - "8000:8000"
        depends_on:
          - postgres
        environment:
            - DJANGO_SETTINGS_MODULE=wellcoders_backend.settings_prod